### PR TITLE
imx-atf-boundary: bump version to 2.6

### PR DESCRIPTION
**Pull request by chrisdimich**
Based upon NXP lf-6.1.1-1.0.0 branch.

### CODE REVIEW

**Comment by chrisdimich** [comment]
No backport to kirkstone needed

**Comment by otavio** [comment]
I think you forgot to add the new file.

**Comment by chrisdimich** [comment]
oops! sorry just pushed it.

**Review by otavio — CHANGES_REQUESTED** [review]
Please add the commit logs.

**Comment by chrisdimich** [comment]
okay done.

**Review by otavio — APPROVED** [review]

**Pull request merged**
