### PR TITLE
Drop broken boards

### PR DESCRIPTION
**Pull request by otavio**

### CODE REVIEW

**Comment by otavio** [comment]
@alexgg

**Comment by otavio** [comment]
@hpalacio

**Comment by alexgg** [comment]
Hi @otavio, what would be required to re-instantiate this support? Just a supported bootloader? The module is supported in upstream barebox so I could give that a go.

**Comment by otavio** [comment]
Isn't it supported on U-Boot? in Digi's fork for example?

**Comment by alexgg** [comment]
hi @otavio the U-Boot version that Digi supports for the Connectcore 6UL is v2017.03, which is the one you removed.
Updating bootloader is usually more pain than gain, first because its job in a production device is just to launch the OS and go away, and then because updating bootloaders in the field is risky unless you have redundant bootloaders which isn't usually the case.

**Pull request merged**
