### PR TITLE
Drop u-boot-*-fw-utils recipes as libubootenv works as replacement

### PR DESCRIPTION
**Pull request by otavio**
Now we are using libubootenv and dropped the u-boot-*-fw-utils, we need
to move the configuration file to the main recipes.

### CODE REVIEW

**Comment by otavio** [comment]
@gibsson @MaxKrummenacher 

Please review this.

**Comment by gibsson** [comment]
Looks good to me. Thanks!

**Comment by MaxKrummenacher** [comment]
Hi

I tried it out.

- It actually doesn't work for all our boards with eMMC, as a negative offset setting in fw_env.config is not supported yet.
https://gitlab.denx.de/u-boot/u-boot/-/commit/f4742ca0fb94e531b8dcddd1ac0799ee4c9c2605
I will send a patch to the libubootenv mailing list which ports the above commit.

- Deploying a file with the default environment would probably also be a good thing.  If the environment has not been saved to storage, e.g. the deployment scenario doesn't do it and no one did use 'saveenv' then libubootenv falls back to read defaults from a file. By default /etc/u-boot-initial-env. If that fails no environment reading or writing is possible.
We already create the file with our downstream U-Boot recipe for use by our installer, I will check how that can additionally be deployed. (make u-boot-initial-env)

**Comment by otavio** [comment]
It just needs to be installed. The u-boot-default-env provides that. Install that and it will do the trick.

**Pull request merged**
