### PR TITLE
u-boot-boundary: fix fw_env.config support

### PR DESCRIPTION
**Pull request by gibsson**
1- first patch changes nxp-bsp to generic-bsp wrt fw_env.config as it applies to both
2- second patch changes arm/aarch64 folders into a storage naming
  -> also fixing the nitrogen8mp fw_env.config as it's using mmcblk2 instead of mmcblk0
  -> this patch should be backported to Honister, but won't apply due to the nxp/generic bsp change, here is it's honister counterpart: https://github.com/boundarydevices/meta-freescale-3rdparty/commit/3ddf02e3f528cd3a048a131f650cff70e3e998c1

### CODE REVIEW

**Comment by otavio** [comment]
The renaming of directories seems confusing for new users. I understand you are trying to reduce code duplication, but it will be harder for users to customize it in their product layers. I want to propose you use them in three directories:

- `mx6-generic-bsp` 
- `mx7-generic-bsp`
- `mx8-generic-bsp`

Otherwise, they will need to check the override to figure out which file is used as `fw_env.config`.

Once we merge this in `master`, you can prepare a PR for the backport.

**Comment by gibsson** [comment]
But that approach doesn't fix my main issue which is that inside the mx8 family, some are using mmcblk0 and some are using mmcblk2. So having a `mx8-generic-bsp` folder won't help.

**Comment by otavio** [comment]
So use the SoC-specific override for the i.MX8 devices.

**Comment by gibsson** [comment]
Is something like that a better approach?

**Comment by gibsson** [comment]
Indeed it works without those. Thanks

**Review by otavio — APPROVED** [review]

**Pull request merged**
