### PR TITLE
u-boot-boundary: bump revision to 181aa1693e1

### PR DESCRIPTION
**Pull request by gibsson**
Main updates are:
- Support KSZ PHY update for latest board rev
- Better display support (both MIPI & HDMI)
- Add preboot command support
- Add gzip bmp display support
- Add erase env command

### CODE REVIEW

**Comment by otavio** [comment]
@gibsson please upgrade `master` branch first, then we prepare backports.

**Comment by gibsson** [comment]
It doesn't apply here, the master version is not the same one as dunfell (2020.10 vs 2022.04).
We can't update dunfell to 2022.04 now, but since dunfell is LTS we still need to update it's version.

**Comment by otavio** [comment]
Good but the equivalent bump is done in master?

**Comment by otavio** [comment]
Thanks for clarifying it.

**Comment by gibsson** [comment]
No problem, thanks for the quick turnaround!

**Pull request merged**
