### PR TITLE
Rework bootscript packaging

### PR DESCRIPTION
**Pull request by otavio**

### CODE REVIEW

**Comment by otavio** [comment]
@MaxKrummenacher please take a look.

**Comment by MaxKrummenacher** [comment]
My idea of providing a custom boot script was a bbappend to the recipe which uses FILESEXTRAPATHS or SRC_URI. 
Allowing to use PREFERRED_PROVIDER_virtual/bootscript looks like a good alternative for more complex cases.

What I don't understand is why one would need the first commit at all. Besides adding complexity and the need to know of the deeper workings of bitbake I don't see any real change or advantage.

What I noticed is that with the move to meta-freescale-3rdparty the recipe got a version. I would change that the version to 1.0 as it is not tied to the U-Boot version. I expect the script doesn't need any change when the U-Boot version changes. Could you do the file name change or should I send a seperate MR?

**Comment by otavio** [comment]
> My idea of providing a custom boot script was a bbappend to the recipe which uses FILESEXTRAPATHS or SRC_URI.
> Allowing to use PREFERRED_PROVIDER_virtual/bootscript looks like a good alternative for more complex cases.

The `bbappend` way still works.

> What I don't understand is why one would need the first commit at all. Besides adding complexity and the need to know of the deeper workings of bitbake I don't see any real change or advantage.

We may want to replace it fully (and we will) and reuse our script for multiple vendors/boards. Also, it is more aligned with how the OE is designed to work.

> What I noticed is that with the move to meta-freescale-3rdparty the recipe got a version. I would change that version to 1.0 as it is not tied to the U-Boot version. I expect the script doesn't need any change when the U-Boot version changes. Could you do the file name change or should I send a separate MR?

You can do that, however, as it was merged already you'll need to set the epoch to 1 (e.g: `PE = "1"`) or it will break package feeds.

**Comment by MaxKrummenacher** [comment]
> We may want to replace it fully (and we will) and reuse our script for multiple vendors/boards. Also, it > is more aligned with how the OE is designed to work.

So its best to keep the recipe in our BSP too and point to that one for our boards and wait and see what happens here with the move to a more generic boot script.

**Comment by otavio** [comment]
Well, you could use the one we have now and it ought to work just fine for your current use. 

As I discussed on Skype with you, I hope Toradex reduces the fork and not increase it.

**Pull request merged**
